version: '3.4'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: StoneChallengePayslipDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: development
    ports:
      - 3307:3307
    volumes: 
      - db_data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
  api:
    image: payslip-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        db:
            condition: service_healthy
    ports:
      - 80:80
      
volumes:
    db_data: