version: '3.3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: StoneChallengePayslipDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: development
    ports:
      - 3307:3307
    volumes: 
      - db_data:/var/lib/mysql
  api:
    image: payslip-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 80:80
      
volumes:
    db_data:    