// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoneChallenge_Payslip.Infra.Data.Context;

namespace Data.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("StoneChallenge_Payslip.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Admission")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Admission");

                    b.Property<bool>("CommuterBenefits")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("CommuterBenefits");

                    b.Property<bool>("DentalPlan")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("DentalPlan");

                    b.Property<string>("Department")
                        .HasColumnType("longtext")
                        .HasColumnName("Department");

                    b.Property<bool>("HealthPlan")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("HealthPlan");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Identification");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("LastName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<double>("Salary")
                        .HasColumnType("double")
                        .HasColumnName("Salary");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
